#pragma once

#include "driver/gpio.h"
#include "component_types.h"
#include "sdkconfig.h"

/* ---------- Helper flags ---------- */

/* GPIO2 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_ANALOG
#define GPIO2_OUTPUT_ANALOG 1
#else
#define GPIO2_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_BINARY
#define GPIO2_OUTPUT_BINARY 1
#else
#define GPIO2_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_INPUT_BINARY
#define GPIO2_INPUT_BINARY 1
#else
#define GPIO2_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_INPUT_ANALOG
#define GPIO2_INPUT_ANALOG 1
#else
#define GPIO2_INPUT_ANALOG 0
#endif

/* GPIO4 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_ANALOG
#define GPIO4_OUTPUT_ANALOG 1
#else
#define GPIO4_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_BINARY
#define GPIO4_OUTPUT_BINARY 1
#else
#define GPIO4_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY
#define GPIO4_INPUT_BINARY 1
#else
#define GPIO4_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_ANALOG
#define GPIO4_INPUT_ANALOG 1
#else
#define GPIO4_INPUT_ANALOG 0
#endif

/* GPIO5 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_OUTPUT_ANALOG
#define GPIO5_OUTPUT_ANALOG 1
#else
#define GPIO5_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_OUTPUT_BINARY
#define GPIO5_OUTPUT_BINARY 1
#else
#define GPIO5_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_INPUT_BINARY
#define GPIO5_INPUT_BINARY 1
#else
#define GPIO5_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_INPUT_ANALOG
#define GPIO5_INPUT_ANALOG 1
#else
#define GPIO5_INPUT_ANALOG 0
#endif

/* GPIO16 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_OUTPUT_ANALOG
#define GPIO16_OUTPUT_ANALOG 1
#else
#define GPIO16_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_OUTPUT_BINARY
#define GPIO16_OUTPUT_BINARY 1
#else
#define GPIO16_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_INPUT_BINARY
#define GPIO16_INPUT_BINARY 1
#else
#define GPIO16_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_INPUT_ANALOG
#define GPIO16_INPUT_ANALOG 1
#else
#define GPIO16_INPUT_ANALOG 0
#endif

/* GPIO17 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_OUTPUT_ANALOG
#define GPIO17_OUTPUT_ANALOG 1
#else
#define GPIO17_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_OUTPUT_BINARY
#define GPIO17_OUTPUT_BINARY 1
#else
#define GPIO17_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_INPUT_BINARY
#define GPIO17_INPUT_BINARY 1
#else
#define GPIO17_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_INPUT_ANALOG
#define GPIO17_INPUT_ANALOG 1
#else
#define GPIO17_INPUT_ANALOG 0
#endif

/* GPIO18 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_OUTPUT_ANALOG
#define GPIO18_OUTPUT_ANALOG 1
#else
#define GPIO18_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_OUTPUT_BINARY
#define GPIO18_OUTPUT_BINARY 1
#else
#define GPIO18_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_INPUT_BINARY
#define GPIO18_INPUT_BINARY 1
#else
#define GPIO18_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_INPUT_ANALOG
#define GPIO18_INPUT_ANALOG 1
#else
#define GPIO18_INPUT_ANALOG 0
#endif

/* ---------- Counts ---------- */

#define OUTPUT_ANALOG_COUNT \
    (GPIO2_OUTPUT_ANALOG + GPIO4_OUTPUT_ANALOG + GPIO5_OUTPUT_ANALOG + \
     GPIO16_OUTPUT_ANALOG + GPIO17_OUTPUT_ANALOG + GPIO18_OUTPUT_ANALOG)

#define OUTPUT_BINARY_COUNT \
    (GPIO2_OUTPUT_BINARY + GPIO4_OUTPUT_BINARY + GPIO5_OUTPUT_BINARY + \
     GPIO16_OUTPUT_BINARY + GPIO17_OUTPUT_BINARY + GPIO18_OUTPUT_BINARY)

#define INPUT_BINARY_COUNT \
    (GPIO2_INPUT_BINARY + GPIO4_INPUT_BINARY + GPIO5_INPUT_BINARY + \
     GPIO16_INPUT_BINARY + GPIO17_INPUT_BINARY + GPIO18_INPUT_BINARY)

#define INPUT_ANALOG_COUNT \
    (GPIO2_INPUT_ANALOG + GPIO4_INPUT_ANALOG + GPIO5_INPUT_ANALOG + \
     GPIO16_INPUT_ANALOG + GPIO17_INPUT_ANALOG + GPIO18_INPUT_ANALOG)

typedef struct {
    gpio_num_t gpio;
    component_type_t type;
    gpio_pull_mode_t pull_mode;
} component_config_t;

static const component_config_t COMPONENTS[] = {

#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_ANALOG
    { GPIO_NUM_2, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_BINARY
    { GPIO_NUM_2, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_INPUT_BINARY
    {
        GPIO_NUM_2,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO2_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_INPUT_ANALOG
    { GPIO_NUM_2, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_ANALOG
    { GPIO_NUM_4, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_BINARY
    { GPIO_NUM_4, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY
    {
        GPIO_NUM_4,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_ANALOG
    { GPIO_NUM_4, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_OUTPUT_ANALOG
    { GPIO_NUM_5, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_OUTPUT_BINARY
    { GPIO_NUM_5, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_INPUT_BINARY
    {
        GPIO_NUM_5,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO5_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO5_INPUT_ANALOG
    { GPIO_NUM_5, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_OUTPUT_ANALOG
    { GPIO_NUM_16, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_OUTPUT_BINARY
    { GPIO_NUM_16, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_INPUT_BINARY
    {
        GPIO_NUM_16,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO16_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO16_INPUT_ANALOG
    { GPIO_NUM_16, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_OUTPUT_ANALOG
    { GPIO_NUM_17, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_OUTPUT_BINARY
    { GPIO_NUM_17, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_INPUT_BINARY
    {
        GPIO_NUM_17,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO17_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO17_INPUT_ANALOG
    { GPIO_NUM_17, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_OUTPUT_ANALOG
    { GPIO_NUM_18, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_OUTPUT_BINARY
    { GPIO_NUM_18, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_INPUT_BINARY
    {
        GPIO_NUM_18,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO18_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO18_INPUT_ANALOG
    { GPIO_NUM_18, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif
};

#define COMPONENT_COUNT (sizeof(COMPONENTS) / sizeof(COMPONENTS[0]))