#pragma once

#include <stdbool.h>
#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"

#include "component_types.h"
#include "sdkconfig.h"

/* ---------- Helper flags ---------- */

/* GPIO2 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_ANALOG
#define GPIO2_OUTPUT_ANALOG 1
#else
#define GPIO2_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_BINARY
#define GPIO2_OUTPUT_BINARY 1
#else
#define GPIO2_OUTPUT_BINARY 0
#endif

/* GPIO4 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_ANALOG
#define GPIO4_OUTPUT_ANALOG 1
#else
#define GPIO4_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_BINARY
#define GPIO4_OUTPUT_BINARY 1
#else
#define GPIO4_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY
#define GPIO4_INPUT_BINARY 1
#else
#define GPIO4_INPUT_BINARY 0
#endif

/* GPIO25 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_OUTPUT_ANALOG
#define GPIO25_OUTPUT_ANALOG 1
#else
#define GPIO25_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_OUTPUT_BINARY
#define GPIO25_OUTPUT_BINARY 1
#else
#define GPIO25_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_INPUT_BINARY
#define GPIO25_INPUT_BINARY 1
#else
#define GPIO25_INPUT_BINARY 0
#endif

/* GPIO26 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_OUTPUT_ANALOG
#define GPIO26_OUTPUT_ANALOG 1
#else
#define GPIO26_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_OUTPUT_BINARY
#define GPIO26_OUTPUT_BINARY 1
#else
#define GPIO26_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_INPUT_BINARY
#define GPIO26_INPUT_BINARY 1
#else
#define GPIO26_INPUT_BINARY 0
#endif

/* GPIO27 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_OUTPUT_ANALOG
#define GPIO27_OUTPUT_ANALOG 1
#else
#define GPIO27_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_OUTPUT_BINARY
#define GPIO27_OUTPUT_BINARY 1
#else
#define GPIO27_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_INPUT_BINARY
#define GPIO27_INPUT_BINARY 1
#else
#define GPIO27_INPUT_BINARY 0
#endif

/* GPIO32 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_OUTPUT_ANALOG
#define GPIO32_OUTPUT_ANALOG 1
#else
#define GPIO32_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_OUTPUT_BINARY
#define GPIO32_OUTPUT_BINARY 1
#else
#define GPIO32_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_BINARY
#define GPIO32_INPUT_BINARY 1
#else
#define GPIO32_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_ANALOG
#define GPIO32_INPUT_ANALOG 1
#else
#define GPIO32_INPUT_ANALOG 0
#endif

/* GPIO33 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_OUTPUT_ANALOG
#define GPIO33_OUTPUT_ANALOG 1
#else
#define GPIO33_OUTPUT_ANALOG 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_OUTPUT_BINARY
#define GPIO33_OUTPUT_BINARY 1
#else
#define GPIO33_OUTPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_BINARY
#define GPIO33_INPUT_BINARY 1
#else
#define GPIO33_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_ANALOG
#define GPIO33_INPUT_ANALOG 1
#else
#define GPIO33_INPUT_ANALOG 0
#endif

/* GPIO34 */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO34_INPUT_BINARY
#define GPIO34_INPUT_BINARY 1
#else
#define GPIO34_INPUT_BINARY 0
#endif

#ifdef CONFIG_FEATURE_COMPONENT_GPIO34_INPUT_ANALOG
#define GPIO34_INPUT_ANALOG 1
#else
#define GPIO34_INPUT_ANALOG 0
#endif

/* ---------- Counts ---------- */

#define OUTPUT_ANALOG_COUNT \
    (GPIO2_OUTPUT_ANALOG + GPIO4_OUTPUT_ANALOG + GPIO25_OUTPUT_ANALOG + GPIO26_OUTPUT_ANALOG + \
     GPIO27_OUTPUT_ANALOG + GPIO32_OUTPUT_ANALOG + GPIO33_OUTPUT_ANALOG)

#define OUTPUT_BINARY_COUNT \
    (GPIO2_OUTPUT_ANALOG + GPIO4_OUTPUT_ANALOG + GPIO25_OUTPUT_ANALOG + GPIO26_OUTPUT_ANALOG + \
     GPIO27_OUTPUT_ANALOG + GPIO32_OUTPUT_ANALOG + GPIO33_OUTPUT_ANALOG)

#define INPUT_BINARY_COUNT \
    (GPIO4_INPUT_BINARY + GPIO25_INPUT_BINARY + GPIO26_INPUT_BINARY + GPIO27_INPUT_BINARY + \
     GPIO32_INPUT_BINARY + GPIO33_INPUT_BINARY + GPIO34_INPUT_BINARY)

#define INPUT_ANALOG_COUNT \
    (GPIO32_INPUT_ANALOG + GPIO33_INPUT_ANALOG + GPIO34_INPUT_ANALOG)

/* ---------- Pin Configuration ---------- */

typedef struct {
    gpio_num_t gpio;
    component_type_t type;
    gpio_pull_mode_t pull_mode;
} component_config_t;

typedef struct {
    gpio_num_t gpio;
    adc_unit_t unit;
    adc_channel_t channel;
} adc_config_t;

static const component_config_t COMPONENTS[] = {

/* GPIO02 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_ANALOG
    { GPIO_NUM_2, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO2_OUTPUT_BINARY
    { GPIO_NUM_2, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif

/* GPIO04 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_ANALOG
    { GPIO_NUM_4, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_OUTPUT_BINARY
    { GPIO_NUM_4, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY
    {
        GPIO_NUM_4,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO4_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif

/* GPIO25 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_OUTPUT_ANALOG
    { GPIO_NUM_25, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_OUTPUT_BINARY
    { GPIO_NUM_25, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_INPUT_BINARY
    {
        GPIO_NUM_25,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO25_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO25_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif

/* GPIO26 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_OUTPUT_ANALOG
    { GPIO_NUM_26, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_OUTPUT_BINARY
    { GPIO_NUM_26, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_INPUT_BINARY
    {
        GPIO_NUM_26,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO26_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO26_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif

/* GPIO27 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_OUTPUT_ANALOG
    { GPIO_NUM_27, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_OUTPUT_BINARY
    { GPIO_NUM_27, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_INPUT_BINARY
    {
        GPIO_NUM_27,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO27_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO27_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif

/* GPIO32 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_OUTPUT_ANALOG
    { GPIO_NUM_32, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_OUTPUT_BINARY
    { GPIO_NUM_32, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_BINARY
    {
        GPIO_NUM_32,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_ANALOG
    { GPIO_NUM_32, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

/* GPIO33 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_OUTPUT_ANALOG
    { GPIO_NUM_33, COMPONENT_OUTPUT_ANALOG, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_OUTPUT_BINARY
    { GPIO_NUM_33, COMPONENT_OUTPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_BINARY
    {
        GPIO_NUM_33,
        COMPONENT_INPUT_BINARY,
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_BINARY_PULLUP
        GPIO_PULLUP_ONLY
#elif defined(CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_BINARY_PULLDOWN)
        GPIO_PULLDOWN_ONLY
#else
        GPIO_FLOATING
#endif
    },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_ANALOG
    { GPIO_NUM_33, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif

/* GPIO34 Config */
#ifdef CONFIG_FEATURE_COMPONENT_GPIO34_INPUT_BINARY
    { GPIO_NUM_34, COMPONENT_INPUT_BINARY, GPIO_FLOATING },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO34_INPUT_ANALOG
    { GPIO_NUM_34, COMPONENT_INPUT_ANALOG, GPIO_FLOATING },
#endif
};

#define COMPONENT_COUNT (sizeof(COMPONENTS) / sizeof(COMPONENTS[0]))

static const adc_config_t ADC_CONFIG[] = {
#ifdef CONFIG_FEATURE_COMPONENT_GPIO32_INPUT_ANALOG
    { GPIO_NUM_32, ADC_UNIT_1, ADC_CHANNEL_4 },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO33_INPUT_ANALOG
    { GPIO_NUM_33, ADC_UNIT_1, ADC_CHANNEL_5 },
#endif
#ifdef CONFIG_FEATURE_COMPONENT_GPIO34_INPUT_ANALOG
    { GPIO_NUM_34, ADC_UNIT_1, ADC_CHANNEL_6 },
#endif
};

#define ADC_CONFIG_COUNT (sizeof(ADC_CONFIG) / sizeof(ADC_CONFIG[0]))